/** @flow */

import './Spacing.css';

const Spacing = {
  margin: {
    bottom: {
      n4: 'Spacing-margin-bottom-4',
      n8: 'Spacing-margin-bottom-8',
      n12: 'Spacing-margin-bottom-12',
      n16: 'Spacing-margin-bottom-16',
      n20: 'Spacing-margin-bottom-20',
      n24: 'Spacing-margin-bottom-24',
      n28: 'Spacing-margin-bottom-28',
      n32: 'Spacing-margin-bottom-32',
      n36: 'Spacing-margin-bottom-36',
      n40: 'Spacing-margin-bottom-40',
    },
    top: {
      n4: 'Spacing-margin-top-4',
      n8: 'Spacing-margin-top-8',
      n12: 'Spacing-margin-top-12',
      n16: 'Spacing-margin-top-16',
      n20: 'Spacing-margin-top-20',
      n24: 'Spacing-margin-top-24',
      n28: 'Spacing-margin-top-28',
      n32: 'Spacing-margin-top-32',
      n36: 'Spacing-margin-top-36',
      n40: 'Spacing-margin-top-40',
    },
    left: {
      n4: 'Spacing-margin-left-4',
      n8: 'Spacing-margin-left-8',
      n12: 'Spacing-margin-left-12',
      n16: 'Spacing-margin-left-16',
      n20: 'Spacing-margin-left-20',
      n24: 'Spacing-margin-left-24',
      n28: 'Spacing-margin-left-28',
      n32: 'Spacing-margin-left-32',
      n36: 'Spacing-margin-left-36',
      n40: 'Spacing-margin-left-40',
    },
    right: {
      n4: 'Spacing-margin-right-4',
      n8: 'Spacing-margin-right-8',
      n12: 'Spacing-margin-right-12',
      n16: 'Spacing-margin-right-16',
      n20: 'Spacing-margin-right-20',
      n24: 'Spacing-margin-right-24',
      n28: 'Spacing-margin-right-28',
      n32: 'Spacing-margin-right-32',
      n36: 'Spacing-margin-right-36',
      n40: 'Spacing-margin-right-40',
    },
    horiz: {
      n4: 'Spacing-margin-left-4 Spacing-margin-right-4',
      n8: 'Spacing-margin-left-8 Spacing-margin-right-8',
      n12: 'Spacing-margin-left-12 Spacing-margin-right-12',
      n16: 'Spacing-margin-left-16 Spacing-margin-right-16',
      n20: 'Spacing-margin-left-20 Spacing-margin-right-20',
      n24: 'Spacing-margin-left-24 Spacing-margin-right-24',
      n28: 'Spacing-margin-left-28 Spacing-margin-right-28',
      n32: 'Spacing-margin-left-32 Spacing-margin-right-32',
      n36: 'Spacing-margin-left-36 Spacing-margin-right-36',
      n40: 'Spacing-margin-left-40 Spacing-margin-right-40',
    },
    vert: {
      n4: 'Spacing-margin-top-4 Spacing-margin-bottom-4',
      n8: 'Spacing-margin-top-8 Spacing-margin-bottom-8',
      n12: 'Spacing-margin-top-12 Spacing-margin-bottom-12',
      n16: 'Spacing-margin-top-16 Spacing-margin-bottom-16',
      n20: 'Spacing-margin-top-20 Spacing-margin-bottom-20',
      n24: 'Spacing-margin-top-24 Spacing-margin-bottom-24',
      n28: 'Spacing-margin-top-28 Spacing-margin-bottom-28',
      n32: 'Spacing-margin-top-32 Spacing-margin-bottom-32',
      n36: 'Spacing-margin-top-36 Spacing-margin-bottom-36',
      n40: 'Spacing-margin-top-40 Spacing-margin-bottom-40',
    },
  },
  padding: {
    bottom: {
      n4: 'Spacing-padding-bottom-4',
      n8: 'Spacing-padding-bottom-8',
      n12: 'Spacing-padding-bottom-12',
      n16: 'Spacing-padding-bottom-16',
      n20: 'Spacing-padding-bottom-20',
      n24: 'Spacing-padding-bottom-24',
      n28: 'Spacing-padding-bottom-28',
      n32: 'Spacing-padding-bottom-32',
      n36: 'Spacing-padding-bottom-36',
      n40: 'Spacing-padding-bottom-40',
    },
    top: {
      n4: 'Spacing-padding-top-4',
      n8: 'Spacing-padding-top-8',
      n12: 'Spacing-padding-top-12',
      n16: 'Spacing-padding-top-16',
      n20: 'Spacing-padding-top-20',
      n24: 'Spacing-padding-top-24',
      n28: 'Spacing-padding-top-28',
      n32: 'Spacing-padding-top-32',
      n36: 'Spacing-padding-top-36',
      n40: 'Spacing-padding-top-40',
    },
    left: {
      n4: 'Spacing-padding-left-4',
      n8: 'Spacing-padding-left-8',
      n12: 'Spacing-padding-left-12',
      n16: 'Spacing-padding-left-16',
      n20: 'Spacing-padding-left-20',
      n24: 'Spacing-padding-left-24',
      n28: 'Spacing-padding-left-28',
      n32: 'Spacing-padding-left-32',
      n36: 'Spacing-padding-left-36',
      n40: 'Spacing-padding-left-40',
    },
    right: {
      n4: 'Spacing-padding-right-4',
      n8: 'Spacing-padding-right-8',
      n12: 'Spacing-padding-right-12',
      n16: 'Spacing-padding-right-16',
      n20: 'Spacing-padding-right-20',
      n24: 'Spacing-padding-right-24',
      n28: 'Spacing-padding-right-28',
      n32: 'Spacing-padding-right-32',
      n36: 'Spacing-padding-right-36',
      n40: 'Spacing-padding-right-40',
    },
    horiz: {
      n4: 'Spacing-padding-left-4 Spacing-padding-right-4',
      n8: 'Spacing-padding-left-8 Spacing-padding-right-8',
      n12: 'Spacing-padding-left-12 Spacing-padding-right-12',
      n16: 'Spacing-padding-left-16 Spacing-padding-right-16',
      n20: 'Spacing-padding-left-20 Spacing-padding-right-20',
      n24: 'Spacing-padding-left-24 Spacing-padding-right-24',
      n28: 'Spacing-padding-left-28 Spacing-padding-right-28',
      n32: 'Spacing-padding-left-32 Spacing-padding-right-32',
      n36: 'Spacing-padding-left-36 Spacing-padding-right-36',
      n40: 'Spacing-padding-left-40 Spacing-padding-right-40',
    },
    vert: {
      n4: 'Spacing-padding-top-4 Spacing-padding-bottom-4',
      n8: 'Spacing-padding-top-8 Spacing-padding-bottom-8',
      n12: 'Spacing-padding-top-12 Spacing-padding-bottom-12',
      n16: 'Spacing-padding-top-16 Spacing-padding-bottom-16',
      n20: 'Spacing-padding-top-20 Spacing-padding-bottom-20',
      n24: 'Spacing-padding-top-24 Spacing-padding-bottom-24',
      n28: 'Spacing-padding-top-28 Spacing-padding-bottom-28',
      n32: 'Spacing-padding-top-32 Spacing-padding-bottom-32',
      n36: 'Spacing-padding-top-36 Spacing-padding-bottom-36',
      n40: 'Spacing-padding-top-40 Spacing-padding-bottom-40',
    },
  },
};

export default Spacing;
